
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed3;

	private global::Gtk.Label text_hoejde;

	private global::Gtk.Entry textBox_hoejde;

	private global::Gtk.Label text_vaegt;

	private global::Gtk.Entry textBox_vaegt;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.Label text_bmi;

	private global::Gtk.Entry textBox_bmi;

	private global::Gtk.Button button_beregn;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.text_hoejde = new global::Gtk.Label();
		this.text_hoejde.Name = "text_hoejde";
		this.text_hoejde.LabelProp = global::Mono.Unix.Catalog.GetString("Din højde");
		this.fixed3.Add(this.text_hoejde);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.text_hoejde]));
		w1.X = 150;
		w1.Y = 57;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.textBox_hoejde = new global::Gtk.Entry();
		this.textBox_hoejde.CanFocus = true;
		this.textBox_hoejde.Name = "textBox_hoejde";
		this.textBox_hoejde.IsEditable = true;
		this.textBox_hoejde.InvisibleChar = '●';
		this.fixed3.Add(this.textBox_hoejde);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.textBox_hoejde]));
		w2.X = 206;
		w2.Y = 52;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.text_vaegt = new global::Gtk.Label();
		this.text_vaegt.Name = "text_vaegt";
		this.text_vaegt.LabelProp = global::Mono.Unix.Catalog.GetString("Din vægt");
		this.fixed3.Add(this.text_vaegt);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.text_vaegt]));
		w3.X = 152;
		w3.Y = 115;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.textBox_vaegt = new global::Gtk.Entry();
		this.textBox_vaegt.CanFocus = true;
		this.textBox_vaegt.Name = "textBox_vaegt";
		this.textBox_vaegt.IsEditable = true;
		this.textBox_vaegt.InvisibleChar = '●';
		this.fixed3.Add(this.textBox_vaegt);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.textBox_vaegt]));
		w4.X = 206;
		w4.Y = 110;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("cm");
		this.fixed3.Add(this.label6);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label6]));
		w5.X = 370;
		w5.Y = 57;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("kg");
		this.fixed3.Add(this.label7);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label7]));
		w6.X = 371;
		w6.Y = 114;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.text_bmi = new global::Gtk.Label();
		this.text_bmi.Name = "text_bmi";
		this.text_bmi.LabelProp = global::Mono.Unix.Catalog.GetString("Din BMI");
		this.fixed3.Add(this.text_bmi);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.text_bmi]));
		w7.X = 158;
		w7.Y = 215;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.textBox_bmi = new global::Gtk.Entry();
		this.textBox_bmi.CanFocus = true;
		this.textBox_bmi.Name = "textBox_bmi";
		this.textBox_bmi.IsEditable = true;
		this.textBox_bmi.InvisibleChar = '●';
		this.fixed3.Add(this.textBox_bmi);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.textBox_bmi]));
		w8.X = 207;
		w8.Y = 210;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button_beregn = new global::Gtk.Button();
		this.button_beregn.CanFocus = true;
		this.button_beregn.Name = "button_beregn";
		this.button_beregn.UseUnderline = true;
		this.button_beregn.Label = global::Mono.Unix.Catalog.GetString("Beregn BMI");
		this.fixed3.Add(this.button_beregn);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button_beregn]));
		w9.X = 248;
		w9.Y = 156;
		this.Add(this.fixed3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 537;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button_beregn.Clicked += new global::System.EventHandler(this.on_clicked);
	}
}
